apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: istiod
  namespace: kube-system
spec:
  chartName: istio/istiod
  version: "1.20.2"
  namespace: istio-system
  repository:
    url: https://istio-release.storage.googleapis.com/charts
  values: |
    profile: ambient
