apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  chartName: bitnami-sealed-secrets/sealed-secrets
  version: "2.14.2"
  namespace: kube-system
  repository:
    url: https://bitnami-labs.github.io/sealed-secrets
