apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  chartName: longhorn/longhorn
  version: "1.5.3"
  namespace: longhorn-system
  repository:
    url: https://charts.longhorn.io
  values: |
    defaultSettings:
      defaultReplicaCount: 1
    persistence:
      defaultClassReplicaCount: 1
